fraction/oasis

.cspell.json, README.md, docs/roadmap.md, package.json, src/app.js, src/assets/style.css, src/pages/models/lib/cooler.js, src/pages/models/post.js, src/pages/public.js, src/pages/publish-reply-all.js, src/pages/publish-reply.js, src/pages/reply-all.js, src/pages/views/components/post.js, src/pages/views/public.js, src/pages/views/reply-all.js, yarn.lock
**What is the purpose of this pull request?**
This adds *reply all* functionality that creates a non-nested reply to a post. Unfortunately I got carried away and this branch is bigger than I'd like.
**What changes did you make? (brief overview)**
- Fix image URL to reduce maximum size 
- Change `<code>` style to remove red highlight
- Add ssb-tangle
- Switch to AGPL
- Add *reply all* page for HTTP GET
- Add *publish reply all* page for HTTP POST
- Add  *reply all view* for submitting the HTTP POST
- Fix roadmap to accurately portray current status
- Change button hover cursor to pointer
- Fix public view to avoid showing private messages
**Is there anything you'd like reviewers to focus on?**
:man_shrugging:
=> Add reply all (and friends)

src/assets/style.css
**What is the purpose of this pull request?**
Aesthetic change: Give the `Comment` button some breathing room (it currently sits on the bottom of the window).
**What changes did you make? (brief overview)**
I added `margin-bottom: var(--whole);` to the `main` element in `styles.css`.
**Is there anything you'd like reviewers to focus on?**
I'm not sure if there's a more appropriate place for the style. Maybe it would be better to target the `form` element? Please edit as you desire. Thanks!
=> Add bottom margin to lift Comment button

src/pages/models/lib/cooler.js
**What is the purpose of this pull request?** This automatically reconnects the client, starting an SSB service in the background if the connection fails repeatedly. Resolves #40.
**What changes did you make? (brief overview)** Added a check during `connect()` and if the stream is closed, restart the client. If the client can't connect, start the server.
**Is there anything you'd like reviewers to focus on?** Most of the changes are just whitespace changes from the indentation. When looking at *Files changed* you can hit the gear icon and select "hide whitespace changes".
Does this behavior sound right to you?
=> Add automatic reconnection on failure

contrib/Dockerfile
docker file broke with code refactor
just letting js manage server creation.
=> fix docker file now that server.js is gone

CHANGELOG.md, src/index.js, src/models/index.js, src/views/index.js
**What's the problem you solved?** It's frustrating to have to open the CLI or Patchwork just to follow / unfollow feeds.
**What solution are you recommending?** Oasis should handle this natively!
=> Add follow and unfollow

.eslintrc.js, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .stylelintrc, .travis.yml, README.md, contrib/install-systemd-service.js, docs/code-of-conduct.md, docs/contributing.md, docs/install.md, package-lock.json, package.json, src/assets/style.css, src/cli.js, src/http.js, src/index.js, src/models/index.js, src/models/markdown.js, src/ssb.js, src/views/index.js, src/views/post.js, src/views/template.js
**What's the problem you solved?** This module maintains a bunch of linter configurations and opinions. Also, `standard`'s code formatting is sort of niche and only works on JavaScript.
**What solution are you recommending?** I think would be better if these opinions were abstracted into their own module (common-good). Also, I'd like to use Prettier to format code. It's much more popular and also formats CSS / JSON / Markdown / etc), which lets us use ESLint to *only* check for code problems instead of style issues.
For what it's worth, I don't plan to program in the Prettier style, but I'm happy to have my code formatted that way before committing. The big JS style changes are:
- **Semicolons.** This is actually kinda nice because it means that you can make modifications without having …
=> Experiment with common-good module

src/views/index.js
Peers might not have a known name
Look in this order and use the first one that's defined: name, hostname, key.
=> Show peers by name, by host, or by key

package-lock.json, package.json, src/index.js, src/views/template.js
**What's the problem you solved?** Common-Good had a bug in the Prettier glob where the recursion
wasn't working correctly. This meant that we weren't actually testing or fixing some of the deeper files.
**What solution are you recommending?** Update CG to the latest version and run `npm run fix` to fix the linter stuff.
=> Update npm dependencies for new common-good

package-lock.json, src/http.js, src/models/index.js, src/models/markdown.js
Problem: When we don't have any documentation for variable types it's
difficult for both humans and machines to parse our code.
Solution: As discussed in https://github.com/fraction/oasis/issues/78,
adding some JSDoc information on function signatures would be a nice
step in the right direction and could make debugging easier.
=> Add some basic type info with JSDoc

LICENSE
The README says this is AGPL-3.0 but we don't have a standard LICENSE file.
I added this using the Github tool at https://github.com/fraction/oasis/community
=> Add LICENSE file (for AGPL-3.0)

.github/ISSUE_TEMPLATE.md
~~**What's the problem you want to solved?**~~
**What's the problem you want solved?**
**Is there a solution you'd like to recommend?**
=> fix typo in github issue template

src/models.js
Problem: If the user tries to see a thread and the link points to a
message we don't have, then we don't have any way to display anything in
the thread. How could we even know which thread it's in? Resolves #144 
Solution: Throw the error but make it more useful and fix the "non-error
thrown" verbiage that we've inherited from a dependency trying to throw
a non-error.
---
If this diff looks scary, try removing the whitespace. We have to do this because of the weird non-error being thrown by a deeper dependency. :man_facepalming:
=> Make "key not found" error more useful

src/models.js
Problem: The 'Following' page was super slow because we were doing a
MuxRPC request on every single message.
Solution: Do one request to see who we have relationships with, filter
out the people we aren't following, and then check against that list
instead of doing a bunch of MuxRPC calls.
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `curl http://localhost:3000/public/latest/following` | 500.9 ± 163.4 | 392.1 | 881.4 | 1.00 |
| `curl http://localhost:3456/public/latest/following` | 4663.7 ± 184.6 | 4438.6 | 5075.2 | 9.31 ± 3.06 |
=> Make 'Following' page way faster

src/index.js, src/models.js, src/views/template.js
Problem: We shouldn't be showing any strangers on the popular or latest
pages. We shouldn't be showing anyone who's been blocked on any of those
feeds.
Solution: Don't show blocked people on any pages and don't show
strangers on the popular / latest pages.
=> No strangers

src/index.js, src/models.js, src/views/template.js
Problem: @masukomi pointed out that the 'latest' view doesn't show the
awesome slice of content that you'll see if you just look at root posts.
Solution: Let's experiment with them! This commit adds a 'Topics' page
that has the latest root posts from people you're following.
=> Add topics page

src/views/index.js
Problem: Publish was missing! Oops.
Solution: Re-add it.
Resolves https://github.com/fraction/oasis/issues/171
=> Re-add publish to nav menu

src/models.js
Problem: The SSB-About plugin is incompatible with our needs. More info
in the GitHub issue linked below and in the code comments.
Solution: Unfortunately, roll our own alternative to the SSB-About
plugin so that we can be 100% sure that it pulls the latest 'about'
published by an author about themselves and doesn't just skip `false`.
=> Use custom getAbout() to replace SSB-About

README.md, src/cli.js, src/index.js, src/views/index.js
Problem: meta was renamed in the UI to settings, but the URLs say meta
Solution: Rename them to /settings/*
Related to https://github.com/fraction/oasis/issues/158
=> Changes /meta to /settings

README.md
Problem: The previous readme didn't really have very much information
about what Oasis is or what we want it to be. It wasn't very enticing.
Solution: Zoom out a bit and give a top-3 list of features that
distinguishes Oasis from other social networking applications and SSB
applications in general.
=> Improve readme with more details about Oasis

src/assets/style.css, src/index.js, src/views/index.js
Could not publish content warnings from oasis
This thing
=> Add content warning publishing, fixes #191

src/models.js
It's a two-fer. I'd do these individually but I think they should go together.
---
Problem: In the old `cooler.read()` implementation, sources returned
promises, but that isn't the case in the native SSB-Client promise
impelementation. This means that in at least one place, there's a bug
where it tries to call `.then()` on a non-promise.
Solution: Remove promise-based code from streams, which don't require
any special handling anymore.
---
Problem: Any error thrown while looking for thread ancestors was
throwing a "message not found" error, which was incorrect and useless.
This error caused me to his refresh repeatedly, not understanding that I
was publishing multiple messages. Super bad. While investigating this I
found that there's a slightly different problem where someone can post
an …
=> Fix sources bug and thread ancestor bug

docs/roadmap.md
Added ticks for "Content warning" and "Get"
=> Added latest roadmap.md progress

src/index.js, src/models.js, src/views/i18n.js, src/views/index.js
This is my first attempt. Comments welcome but I'm off the train now so I'll be back on... tomorrow or on monday, :P
=> [WIP] raw json submission form

src/index.js
Problem: There wasn't an easy way to copy and paste a message ID, feed
ID, or blob ID and get directed to that page in Oasis.
Solution: When someone pastes one of the above into the search, just
redirect the browser to the correct page rather than searching for that
text.
=> Redirect search to SSB references

docs/AUTHORS, docs/MAINTAINERS
Problem: It's hard to know who has worked on the project and who is
maintaining the project, for security and code of conduct issues.
Solution: Add AUTHORS and MAINTAINERS files to track who has contributed
code and mixed in their copyright (woo!) and keep track of who is
committed to maintaining the project and merging patches.
=> Add AUTHORS and MAINTAINERS files

package-lock.json, package.json, src/index.js, src/views/i18n.js, src/views/index.js
Problem: It was impossible to tell which version of Oasis you're
running, which makes it hard to know when you need to update.
Solution: Put the version in the settings so it's easy to reference.
=> Add Oasis version to settings

docs/translating.md
In #238 someone asked how to add a new language, so I wrote some documentation about that.
=> Add docs/translating.md -- instructions for adding new languages

src/index.js
Problem: We load the default config with `require()`, which would allow
arbitrary JavaScript execution, are producing debug output everywhere
with `console.log()` statements, and don't have instructions for how to
write the config file. The config file is also `.config/**/config.json`,
and I think it would be helpful to specify that this is the **default**
config rather than any other kind of config.
Solution: Rename the config to `~/.config/oasis/default.json`, replace
the `require()` with `fs.readFile()`, remove `console.log()` for
debugging, and add some example JSON for how to use the config file.
cc: @black-puppydog in case you feel very strongly about `~/.config/oasis/config.json` :heart:
=> Refactor default config loader

README.md
Correct the config path on Mac Os.
=> Update README - fix config path on mac os

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This could be just personal preference but I prefer using markdown headers for the template questions. I also thought it would be useful to ask what version people are using for issues.
Updated the templates.
P.s. I am also using this as a chance to test GPG signed commits :smile:
=> Updated Github issue and pull request templates

src/views/i18n.js
Added more spanish translations
=> Added more spanish translations

src/index.js
Cherry-picked version of #305 for @seekr
=> lands on /mentions instead of /public/popular/day

src/views/i18n.js
Cherry-picked version of #304 
cc: @seekr
=> finished spanish i18n

src/views/i18n.js
Some basic tweaking of text.
The changes below.
=> View thread label

src/views/index.js
Settings list is in a bit of an arbitrary order.
Rearrange settings list in order of potentially most likely to use.
=> Rearrange settings

docs/MAINTAINERS
#288 AUTHORS and MAINTAINERS have only one person :)
I feel like a MAINTAINER.  I don't feel like an AUTHOR so I'm not adding myself there - I haven't written much actual code - but if it was renamed to CONTRIBUTORS I would add myself there also.
=> Add myself to MAINTAINERS

docs/CONTRIBUTORS
jump in everyone, the water's fine!
#313
=> Rename AUTHORS to CONTRIBUTORS and add myself

src/views/i18n.js
Posts from yourself show up in certain feeds now. This wasn't mentioned in the feed descriptions.
Added that reference to the descriptions.
=> Small text tweaks

README.md
Patchbay wasn't in list
Add patchbay to list
=> Added patchbay to same time server list

package-lock.json, package.json
Problem: Some sigil links were broken because of a bug in SSB-Markdown
that was recently resolved.
Solution: Upgrade SSB-Markdown.
Fixes: https://github.com/fraction/oasis/issues/242
=> Fix Markdown link bug

src/views/index.js
currently if non-english language is set in configuration, the FOLLOW button doesn't work (it takes the i18n translation as part of the URL).
made the url fixed `*/follow/*` rather than dynamic
=> fix follow button link for non-english languages

src/assets/style.css
=> Revert selector to span to fix lock alignment

docs/architecture.md, docs/contributing.md, docs/maintaining.md
Minor typo, broken link, missing mention of handy pr management via the github cli.
Fix the things
=> minor doc fixes; add gh cli instructions

package-lock.json, src/views/i18n.js, src/views/index.js
Added Italian translation
Double check the Spanish translation to see if there are discrepancies between Castillan and various versions of Spanish used in Southern and Central America.
=> Italian translation, changed a string in the Spanish translation

src/models.js
Problem: The Threads view advertises that it only shows public posts,
but is showing some private posts as well. This is not a security
concern, it's just a UI inconsistency.
Solution: Ensure that private posts are filtered from the view before
rendering. This also integrates a refactor that uses functions to check
for basic info like whether a message is a post, whether it's
encrypted/decrypted, whether it has a root, whether it has a fork, etc.
=> Fix private posts rendered alongside public posts

src/views/index.js
The 'liked by' title (hover) wasn't present in replies in the Threads view; now it is.
post() and postInAside() were basically the same, apart from the missing 'liked by' title in the latter, and an additional "post" css class in the former, so I removed postInAside() and used post() in its place.
The "post" class doesn't seem to do anything, so I left it in for the replies (which now have class = "post reply", instead of just "reply"). Lemme know if I should change this.
=> Fix 'liked by' hover in replies in Thread view

src/views/i18n.js
=> Added french "fr" translation

src/index.js, src/models.js
`blog` type messages were not getting rendered besides the generic JSON dump.
This PR simply loads the blob during the `transform()` call.
I'm unsure though how this everything should be handled in public mode.
The blog message itself might be private, or it might reference a boxed blob... what then?
=> Add rendering of blog messages.

.github/workflows/pr.yml
Problem: PRs are being run twice, once as a push and once as a PR.
Solution: Run only as a push against master or a PR against master.
=> Make GitHub Actions workflow faster

.depcheckrc, package-lock.json, package.json
#497 wasn't passing tests because the version bump was actually incompatible.
Fixing the common-good call, and ignoring the dev type and husky and stylelint dependencies... :P
=> Common good 4.0.3

docs/configuring.md
=> Copying solution to the issue into the docs.

src/models.js, src/views/index.js
In a private message you can't see who the recipients are, so you can't know the audience you're talking to.
Shows recipient thumbnails in the top right corner of each message (see image)
=> Issue 126: Show recipients of private messages

src/models.js
Can see posts from blocked people in threads (Issue https://github.com/fraction/oasis/issues/399)
Add a social filter to threads
=> Add social filter to threads

README.md
Fixes #575
Added to FAQ and See Also sections
=> mention oasis-desktop in the README

src/models.js, src/views/index.js
Fixes #110 
Updated pendingVoters and added filter to getting "likes"
=> updating code for likes page bug
