fraction/oasis

- contrib/oasis.service
**What is the purpose of this pull request?**
I was having a problem where I'd start my computer but the script wasn't
restarting automatically, and after some searching I found this: https://github.com/systemd/systemd/issues/2690#issuecomment-186973730
It looks like we should be using `default.target` instead of
`multi-user.target`.
**What changes did you make? (brief overview)**
Change systemd unit to use `default.target`
**Is there anything you'd like reviewers to focus on?**
Does this look right to you?
> Change systemd unit to use `default.target`

- index.js
- src/pages/models/lib/server.js
This is a new offline branch (the old one `offline-mode` was pretty old, so I started over)
**What is the purpose of this pull request?**
Add `--offline` CLI flag which disables interaction with the SSB network by turning off the conn scheduler.  I believe, but am not 100% certain, this should cover all forms of peer discovery and pub communication.
**What changes did you make? (brief overview)**
* Add `--offline` CLI flag
* Get that config info into `server.js` using global variables 😦  since there isn't a way to pass the config down the dependency chain easily.  I tried to do the simplest thing that would work, expecting this to need cleanup later.
* In `server.js`, set `conn.autostart` to `false` when in offline mode
* Small improvements to CLI help text
**Is there anything you'd like …
> Add CLI flag for offline mode (using temporary hack with globals)

- src/models/index.js
If you stand up a fresh sbot and join a pub you get flooded with messages. Then your /popular/day shows you content from 2 years ago. I believe this to be happening because the `gt:` option is filtering on sync time and not message value time. 
After I made this change /popular/day was showing content from about a week ago in time. I assume this to be because of users interacting with week old content in the current day. I feel fine with this as a outcome.
Adding a message filter that filters on the timestamp inside the message.
> filter messages outside time range

- README.md
**What's the problem you solved?** I've had a few friends have trouble installing Oasis with an older version of Node.js.
**What solution are you recommending?** Add supported versions to the readme in a way that we don't have to update (like version numbers) and link to the Node.js website for people who want to learn more about the release schedule.
> Add note about supported Node.js versions

- src/assets/favicon.svg
- src/views/template.js
When I pin the tab on firefox, the icon shown is generic. I'd love to see the DESERT ISLAND. Left is currently pinned, right is with this patch.
Make an svg favicon. I'd be interested in seeing if it renders correctly in different browsers.
> Create svg favicon

- src/views/index.js
People are often confused about the difference between peer connections and social/following connections
* Added some help text on the Meta page Peers section as mentioned in #68.
* When there are no peers, say "no peers connected" instead of omitting the Peers section
* Moved Peers section before Indexes because I expect people to look at Peers more often than Indexes
> Add help text in Meta about peer connections

- src/index.js
- src/views/index.js
**What's the problem you solved?** #68 
**What solution are you recommending?** This adds names to the peer list. I haven't tested what happens when we don't have someone's name. Maybe we should fall back to the first six characters of their name? Seems like maybe `about.name` should just return that instead of `null` maybe...
> Add prototype for names in peer list

- .travis.yml
- package.json
**What's the problem you solved?** Travis builds PRs and branches, which means that local branches
get built twice (!).
**What solution are you recommending?**  Travis should only build `master`, and maybe tags. This commit also contains the changes from `npm --init`.
> Make Travis faster by removing double-build

- package-lock.json
- package.json
Problem: CG's dependency, CSpell, had problems with Windows support, so
I was using a forked module as an alias to circumvent the problem. This
only works on very recent version of npm.
Solution: This morning the CSpell maintainer resolved the problem, so
the latest CG doesn't have to depend on an alias. This commit runs `npm
update` to get the latest version of CG so we don't have this problem.
Resolves #80
> Update Common-Good to stop using npm alias

- src/models/index.js
The /inbox page was being rendered super slowly because it was
reading through tons of messages.
There isn't a way to query the database for "private messages
for me", although maybe there should be, but one way we can get
something close is querying for "messages that reference me". Every
message that's encrypted for us will have a `.value.content.recps`
property that includes our feed ID, so we just have to filter out the
public messages and we're about 4 times faster than the previous
implementation.
```console
$ hyperfine 'curl -I http://localhost:4515/inbox' 'curl -I http://localhost:3000/inbox'
Benchmark #1: curl -I http://localhost:4515/inbox
Time (mean ± σ):      3.352 s ±  0.093 s    [User: 2.0 ms, System: …
```
> Use ssb-backlinks to improve /inbox page load

- package-lock.json
- package.json
- src/ssb.js
Problem: Patchwork is missing a plugin that we need to set the `branch`
property when posting a message. This property is important because it
helps us sort threads, so we're throwing an error when it isn't
available. See: https://github.com/fraction/oasis/issues/21
Solution: HACK THE ~~PLANET~~ API. This commit injects the plugin we
need via Oasis, which is a bit of a duct tape solution but it *is* a
solution.
> Fix tangle bug when Patchwork is used as a server

- src/assets/favicon.svg
**What's the problem you solved?** Some of the icon was being clipped in my browser. I think that this is because the SVG text actuall extends down under the line (like a `g` or `y`).
**What solution are you recommending?** Change SVG viewBox dimensions and SVG size to fit correctly.
Before and after:
> Change favicon dimensions to fit in tab

- src/assets/style.css
- src/index.js
- src/models/index.js
- src/views/index.js
- src/views/post.js
- src/views/template.js
Problem: Using all-lowercase-everything isn't really a standard around
the web and it might be better to use consistent capitalization. This
was brought up in: https://github.com/fraction/oasis/issues/98
Solution: This changes the main navigation to use links with the first
letter capitalized, like how Patchwork + Twitter + Mastodon + etc do it.
This means that we're consistently using sentence case everywhere, which
I think is our best option. Originally I tried experimenting with
all-caps for actions, which I found aesthetically pleasing, but you have
to reduce the font size to make it look good (bad!) and I was reading
that all-caps text is harder for friends with dyslexia or vision
impairments.
> Use capitalization for Oasis links and buttons

- src/assets/style.css
Problem: Putting the navigation at the top of the screen makes it
impossible to use when you're scrolling through a page, which isn't a
good user experience. It was never meant to be permanent, and I think
everyone has pointed out that it's been a pain. See #28.
Solution: Super simple sidebar nav when people are on bigger screens.
This doesn't solve the problem on mobile, and it doesn't incorporate the
'popular' page's interval settings, but I think it's a step in the right
direction.
> Add simple nav sidebar on large screens

- package-lock.json
- src/index.js
- src/models/index.js
Problem: Showing private posts on profiles is scary and may give people
the impression that these posts are visible.
https://github.com/fraction/oasis/issues/113
Solution: Hide private messages when rendering public profiles and
change the method name to be very clear that it only returns public
messages.
> Hide private messages from author profiles

- docs/contributing.md
Problem: The word "shall" is ambiguous and seems pretentious rather than
friendly. More info here: https://www.plainlanguage.gov/guidelines/conversational/shall-and-must/
Solution: Replace "shall" with "must". It has the same semantics with
none of the ambiguity or cultural baggage.
> Replace "must" with "shall" in contributing.md

- src/views/index.js
#109 Solved some missed capitalization on networking buttons on the Meta page
Recommendation is to capitalize Start, Restart, and Stop.
> Fixed capitalization on networking buttons on Meta page.

- .travis.yml
- package.json
Problem: Targeting only the latest version of Node.js and the latest LTS
means that we have a sort of rolling backward-compatibility that's hard
to reason about. If we break compatibility, we should release those
changes as a major version, but the current strategy makes it difficult
to tell exactly when we're breaking compatibility.
Solution: Specify the exact Node.js versions that we want to support in
`package.json` and add the specific tests to `.travis.yml`. In the
future we can break compatibility if it's helpful but we'll have to do
so explicitly and release the change as a major version.
> Specify exact Node.js engine support and test it

- package-lock.json
- package.json
- src/index.js
Problem: Most browsers parse SVG files as XML and refuse to display it
in an `<img>` tag. It's usually unsafe to have browsers try to sniff the
file type themselves, because they can be tricked into running unsafe
code, so we want to set the file type ourselves in the server.
Solution: Use the Is-SVG library for a quick-n-dirty check for whether a
buffer is an SVG. If so, we set the file type accordingly.
> Fix SVG rendering by setting content-type

- package-lock.json
- package.json
Problem: We aren't using the index at all so Oasis is just wasting time
and CPU power.
Solution: Upgrade Flotilla and resolve the problem.
> Update Flotilla to drop SSB-Links2

- src/index.js
- src/models/index.js
- src/views/template.js
Problem: We don't always want to see all of the messages on our
computer, sometimes we just want to see messages from the people we're
explicitly following. The 'Popular' and 'Latest' pages don't help with
that. See #57 
Solution: Add a super basic page that just shows the latest messages
from the people you're explicitly following.
> Add basic following page

- src/models/index.js
Problem: The popular page is ungodly slow.
Solution: Make it faster! This is done by checking the timestamp before
the other constraints that we add to messages, which is mostly useful
because most messages that fail the filter will fail on the timestamp
check.
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `curl http://localhost:4515/public/popular/year` | 13.159 ± 0.480 | 12.843 | 14.450 | 1.21 ± 0.05 |
| `curl http://localhost:3000/public/popular/year` | 10.866 ± 0.163 | 10.594 | 11.133 | 1.00 |
> Make 'Popular' page faster

- src/assets/style.css
- src/views/index.js
- src/views/template.js
In several issues we've discussed renaming pages in the navbar and changing their order.
This PR:
* Reorders the navbar links to follow the gradient of intimacy from public to private #57 #117
* Renames Inbox --> Private, and Meta --> Settings #116 to be more similar to Mastodon
* Adds emojis because there are now too many items in the navbar list to comprehend at a glance
I'm not sure the emojis are a good idea.  If we don't like them after a couple of days we can remove them in another commit.  This is an accidental stress-test for our C4 process :)
I'd prefer to have simpler monochrome icons that are less distracting.  It was a challenge to find sensical emojis for these concepts.  I was especially trying to …
> Navbar refresh: reorder, rename, add emojis

- src/views/index.js
The "Follow" button was showing on your own profile.
I took a screenshot an hour ago and it wasn't there, and then it was.  Was there a change to capitalize the relationship strings ("You are following" etc)?  It would be good to refactor these relationship strings into constants.
> Remove follow button from your own profile

- README.md
Problem: Help link in readme was pointing to the issue type selection
which is no longer useful because we just have one template. Resolves #56 
Solution: Fix the link and point directly to the issue creation link.
> Fix help link in readme

- docs/blob-security.md
Problem: I still haven't found any best practices for how to run HTML on
your domain without any security concerns. I feel reasonably confident
that our current security precautions mitigate any potential attacks,
but I want to be very up-front with any security mitigations that aren't
so common that they're boring and predictable.  Resolves https://github.com/fraction/oasis/issues/5.
Solution: Add a document to describe our current security model and
mitigations so that we can point at it when asking friends to review the
model and ensure we don't have any holes.
> Add document describing blob security model

- src/assets/style.css
Problem: The nav is aligned to the left of the screen on mobile, which
feels off-center and unbalanced on mobile. Resolves https://github.com/fraction/oasis/issues/135
Solution: Center the menu to optimize for space around the links.
> Fix nav alignment on smaller screens

- README.md
Problem: https://github.com/fraction/oasis/issues/149
Solution: Add note to the readme advertising the npm install straight
from GitHub, which will pull the latest `master`.
> Add bleeding-edge install instructions to readme

- src/http.js
- src/index.js
Problem: I think during a refactor this code was changed and ended up
breaking the "fake image" that we return when the user doesn't have an
image. We also don't see image errors because they aren't in the browser
viewport if they return text and we don't `console.error()` our errors.
Resolves #138?
Solution: Fix the image code to return a PNG as a buffer and duplicate
errors to stderr.
> Fix /image/ URL returning a broken image

- src/assets/style.css
- src/index.js
- src/views/i18n.js
- src/views/index.js
We have a lot of feeds with short names (Topics, Extended...) but it's not clear what they really mean.
This adds a title and descriptive text to most of the feeds:
Added to:
Not changed
* Author profile page (it already has an info card about the author)
* Search (it already has the search box)
Add the remaining pages:
Other things
I also rearranged the i18n strings into a more logical order.  That should have been a separate patch, sorry :)
> Add description of each feed at the top of the page

- src/models.js
Problem: The socialFilter was hiding posts published by the user, which
felt weird and uncanny.
Solution: Fix the default so that `{ me }` isn't hidden from a view
unless the model specifically wants that to happen.
Resolves https://github.com/fraction/oasis/issues/156
> Fix socialFilter() to change `{ me = null }`

- src/assets/style.css
- src/index.js
- src/views/i18n.js
- src/views/index.js
Problem: The Private and Mentions page didn't have view labels yet, and
Publish should be its own page instead of being at the top of every
page.
Solution: Inspired by @cinnamon-bun's work to add friendly view labels,
plus a new Publish page.  This also moves the period selection from the
popular page into the view label, which felt better to me with the
previous `<section>` background. I also tried a different text format
for describing the pages, using a common form and using `<strong>` to
draw attention to any change from "Posts from people you follow, sorted
by recency" which feels like the expected default for most people.
@cinnamon-bun: To me this feels like a fun back-and-forth where I'm
riffing on your work and hoping that you do the same, but if it feels
wrong/rude please let me …
> Add view info for Private, Mentions, and Publish

- src/assets/style.css
- src/views/index.js
Problem: The regular space in the sidebar emoji was breaking the line at
a specific viewport width and the emoji were being shown as the wrong
font.
Solution: Use a non-breaking space and `font-family: initial` for
full-color emoji instead of using the system font.
Resolves https://github.com/fraction/oasis/issues/150
Resolves https://github.com/fraction/oasis/issues/153
> Fix emoji and breaking space in main nav

- src/http.js
Problem: We use nosniff to keep the web browser from getting confused
about what kinds of content we're serving in Oasis, but this causes
problems for blob URLs that have arbitrary data.
Solution: Remove nosniff on blob URLs to let the browser figure out what
kind of content we're serving.
Resolves https://github.com/fraction/oasis/issues/138
Now works in Chromium!
> Remove nosniff from blob URLs

- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: There was no way to onboard new users since we couldn't redeem
invites.
Solution: Add basic follow-back invites to the settings page. This takes
an invite string, runs it through invite.accept, and either returns the
error in full *or* redeems the invite quietly. Resolves #97 
---
Note: This branch contains commits from the other PRs for i18n and such. Once the other PRs are merged I'll squash this and mark it 'Ready for review'.
> Add invite code

- src/models.js
Problem: The `socialFilter()` function wasn't documented and contained a
bug where it wouldn't show your posts when `following = true`. This is
because you usually don't follow yourself, so `following = true` was
basically equivalent to `me = false`.
Solution: Add some documentation and resolve the bug by adding special
handling for when the message is from us *before* passing to the general
implementation for follow/block checking.
Resolves https://github.com/fraction/oasis/issues/155
Resolves https://github.com/fraction/oasis/issues/177
> Fix and document `socialFilter()`

- src/cli.js
- src/index.js
- src/models.js
Problem: It's hard to show off Oasis or take screenshots without
respecting the `publicWebHosting` convention. While `publicWebHosting`
lacks a formal specification and I'm a bit confused about what its
boundaries are, it sounds like some of our friends would like to avoid
us publishing any of their content on the public web if we can avoid it.
Solution: Add --public option that turns Oasis into a public web viewer.
This makes it **slightly inconvenient** to see these public posts, but
should absolutely not be mistaken for a privacy guarantee. Only HTTP GET
endpoints are allowed, so random people can't publish or change
settings. The name, avatar, description, content warning, and message
contents are replaced with "Redacted", but again, this is all public
information that we can never …
> Add --public option for public viewers

- src/index.js
Problem: Search engines are controversial and my understanding is that
most people on SSB don't want their messages indexed by search engines.
If that's the case, we should probably disable it.
Solution: Add basic `robots.txt` file to ask search engines to stay away
and please don't save info. I'm concerned that, like `publicWebHosting`
redactions, it gives a false sense of privacy, but it seems like this is
probably what most people would want?
> Add basic robots.txt to keep search engines away

- src/models.js
Problem: There was one missing component that would filter out nicknames
from other people. This caused a problem where we could get a name for a
feed but it could've been assigned by a friend, which we don't want
right now.
Solution: Ensure that the subject of the message is the same as the
author of the message.
> Fix bug where others could still change your name

- src/models.js
Problem: Your posts show up in Extended, which is unexpected because I'm
the center of my network, not some rando at the periphery.
Solution: Use the `socialFilter()` function to make sure that the
extended view only shows people in your extended network, not you. :)
> Fix extended page so it doesn't show your posts

- src/views/markdown.js
Problem: Emoji from Markdown posts were being displayed in the default
font, which doesn't always use color emoji.
Solution: Use the `.emoji` CSS class on those emoji to ensure that the
correct emoji font is used.
> Use color emoji in Markdown posts

- src/views/index.js
Problem: When replying to a private thread we already know who the
recipients are, and they're already going to get the notification, so
there's really no reason to add a mention.
Solution: Remove the mention when the message is private.
> Remove automatic mentions from private threads

- src/models.js
Problem: Previously we were only counting likes from people you follow,
but showing messages from anyone. This was backward, and could
potentially show messages from blocked authors that were liked by people
you follow.
Solution: Move the `socialFilter()` invocation down the pipeline so that
it sorts the output messages, not the likes.
cc: @georgeowell could you verify that this resolves #202
> Fix popular page to only show posts from following

- src/index.js
Problem: The new content warning code was applying a content warning to
all posts, which tried to publish an invalid content warning `""` and
threw an error.
Solution: Only publish a content warning if it's a string with non-zero
length.
Resolves #211
> Fix publish not working without content warning

- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: The new custom publish was called 'Manual mode', which I'm
afraid isn't super easy to understand for people who don't already know
SSB. The custom publishing page didn't follow the same conventions as
other pages, either.
Solution: Hide the custom publish mode behind the publish page, with a
warning that it's for 'advanced users', and ensure that it uses the same
conventions and visual styles as other pages and code around the app.
> Hide custom publish behind publish menu

- src/models.js
Problem: When we couldn't figure out someone's name or description we
were using `null`, which got coerced to a string and ended up with us
calling people `"@null"`. Not ideal!
Solution: Support a use-case where someone doesn't have a profile
description or a name, and use the first 8 characters of their public
key for their name if they haven't set a name themselves.
> No more `null` for unknown names and descriptions

- .github/workflows/npmpublish.yml
this is just a sketch, and we need to set NPM_AUTH_TOKEN
Its hard to publish on npm
If you change the release number in package.json, and make that commit message "Release x.y.z", this should tag that commit as vx.y.x . I have not tested this at all!
> tag and publish on npm

- .gitignore
- src/assets/style.css
- src/models.js
- src/views/index.js
First of all, I am not familiar with the C4 contribution process, please be patient with me :) I just built this for myself today because I wanted to get familiar with the Oasis codebase and wanted to have this feature myself. If it's not in your vision for Oasis, no problem.
On a large monitor, Oasis is only using a fraction of the horizontal space. Also, I was missing Patchworks feature to show a preview of comments on each post in the timeline.
Example:
Here I have added a preview of comments on each post in the timeline, which is shown to the side of the original post on large screens and below on small screens (as in Patchwork).
Examples:
**Caveats**
- The popular page now takes a long time to load (56sec vs …
> Show a preview of comments in listings

- src/assets/style.css
- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: Until we have a way to change the view of each page, it seems
to me that each of the views that we're experimenting with should be on
their own page rather than modifying the existing pages to add more
functionality. I'm also noticing that I can't process all of the
information that's on the screen when the new horizontal layout is used,
and I think we would benefit from using the previous layout
consistently.
Solution: Move the summary view to its own page so that we can continue
to iterate on it without modifying the popular view, which is already
complex, and revert the style changes to maintain consistency with the
rest of the linear design (threads go downward, indentation denotes
sub-threads, etc).
> Create 'Summaries' page for new summary view

- src/index.js
Problem: After publishing a message you were redirected to the Popular
view, which wasn't good feedback that your message had been published.
Solution: After publishing a new message, redirect to the Latest view.
> Redirect to Latest after publishing new message

- src/index.js
Problem: When the port was already taken by another process we've been
dumping a big esoteric error message that really isn't helpful for most
people.
Solution: Catch the error and give our users a friendly error message
with a suggestion on how to run Oasis on another port.
> Add friendly EADDRINUSE error message

- src/models.js
Problem: Private messages should only be showing up in the Private page,
not the Mentions page, but right now they're showing up in Mentions.
Solution: Add a check to ensure that Mentions doesn't have any private
messages.
> Remove private messages from Mentions

- src/assets/style.css
- src/index.js
Problem: I added an image border to try to make it easier to see the
boundaries of images but it's not really necessary and at least one
person didn't love it, which is grounds for removal.
Solution: Get it out of here! This commit removes the image border and
also removes a random `console.log()` that shouldn't have been left in
`src/index.js`.
> Remove image border

- src/models.js
Problem: The `messagesByType()` queries don't let us sort by asserted
time, which means that we can get messages from a long time ago that
just ended up on our computer.
Solution: Use SSB-Query everywhere. The query syntax isn't really my
favorite but it lets us make declarative queries that respect the
asserted timestamp instead of just the received timestamp.
> Replace messagesByType() with SSB-Query read

- src/models.js
Problem: During the SSB-Query refactor I used `{ private: false }` in an
attempt to hide private messages, but apparently this option is only
available via SSB-Backlinks, so it was ignored without any warning (!).
This allowed private messages to be displayed in public views.
Solution: Remove the unused option and add a filter to public views that
ensures that private messages are always hidden.
cc: @georgeowell
> Remove private posts from public views

- package-lock.json
- package.json
- src/index.js
Problem: We've been using a workaround to filter the results of
SSB-Mentions, but that's just been fixed upstream and so we don't need
the workaround anymore.
Solution: Update the SSB-Mentions package and remove the workaround.
See: https://github.com/ssbc/ssb-mentions/pull/17
> Update SSB-Mentions and remove workaround

- .cspell.json
- src/ssb.js
Problem: We're doing tons of unnecessary cryptography by encrypting the
connection between the "client" and "server", which are often running in
the same process.
Solution: Instead of connecting to the SSB service over TCP and
encrypting the stream, just connect over a socket (supported on Windows,
macOS, and Linux) and don't bother encrypting anything. This is what
Patchwork and Patchbay do already, and since our secret is at
`~/.ssb/secret` then we should be comfortable with `~/.ssb/socket` being
a trusted file where access implies authentication.
Local tests suggest that when sodium-native is available, this commit
reduces the time to render the 'Popular (Day)' page by 17%, but when we
have to fall back to JavaScript cryptography the same page now takes 30%
less time to render. My …
> Add support for Unix socket with noauth

- package-lock.json
- package.json
- src/cli.js
- src/index.js
This should give pretty much expected behaviour. Each config value
can be set by three sources:
1. By command-line argument. If it is not given, then
2. By config file. Or, lastly
3. By default value in the source code.
I can't test that the config file is searched and read from the right
place on windows or macOS, but on linux it works.
> Read settings from $XDG_CONFIG_HOME/oasis/config.json

- README.md
- src/cli.js
- src/index.js
Lack of documentation of how/where configuration is stored.
As @cinnamon-bun suggested...
* I added a few lines to the readme, 
* added a few lines to the `--help` text, and also 
* added output of current configuration location and values.
Had to coerce c-spell into ignoring the unknown word "APPDATA" and even though `prettylint` didn't complain, prettier did (but didn't say what's wrong) so I bypassed the pre-commit hook on this one.
More importantly though: I'm not 100% certain about the config location on Mac OS and Windows, I went with the `env-paths` docs on that one. So if someone could verify that would be cool. 
Good night :)
> Add config documentation (addresses #254).

- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: Searching for a hashtag should bring you to the hashtag page,
and the hashtag page should have some useful information about which
page you're on instead of just showing you the messages.
Solution: Add code so that if you search for a hashtag you're brought to
that page, and display some useful help text at the top of the page
explaining the hashtag page. While ensuring that the hashtag page showed
posts from around the network (instead of only people you're following)
I fixed the popular page so that it has the same behavior again (fixing
a regression) and filtered out gatherings (fixing *another* regression)
on the popular page. These probably should've happened in another commit
but I got carried away. :/
Happy to split this commit into two if it hurts to bundle the popular …
> Add hashtag support to search

- src/models.js
Problem: The search results weren't hiding results from blocked feeds.
Solution: Add `socialFilter()` to ensure that all blocked feeds are
removed from search results as the first step in the stream processing.
> Hide search results from blocked feeds

- src/index.js
Problem: Sometimes you try to run Oasis twice and the second time you
run the program it blows up in your face about the port being taken.
Most other software just focuses or reopens the window instead of
throwing errors at you.
Solution: Implement `/.well-known/oasis` as a sanity check to see
whether the thing listening on the HTTP port. If it replies "oasis" then
we can open the tab (unless `config.open === false`) and avoid throwing
the error.
> Detect existing Oasis server running on interface

- src/models.js
Problem: Trying to use the DTA index when using SSB-Query doesn't work,
because that index only exists on SSB-Backlinks.
Solution: Change the filter to ensure that we're sorted by the asserted
timestamp and ignoring messages from the future. The SSB-Backlinks
plugin was taking the minimum between `.value.timestamp` and `timestamp`
but since we're not using SSB-Backlinks in this query (or maybe at all?)
we get to make our own little hacky query. Cel taught me that the
`$sort` option causes problems here because it buffers the entire result
in memory before doing the sort. Boo. Instead we just need to reference
the property that we want to be sorted by with some operation, even if
it does nothing (like `{ $gt: null }`), but since we're filtering time
travelers we actually need `{ $lge: …
> Fix queries with an unused `{index: "DTA"}` option

- src/assets/style.css
- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: An SSB client should allow you to declare your own name, but
Oasis didn't support that behavior at all.
Solution: Add a basic 'Edit Profile' page that lets you set your name
and description. This doesn't implement profile images because I had
limited time and didn't want to think about encoding formats, but it's
worth mentioning that I remember something about binary uploads with the
default form encoding actually send 3 times as much data because of
escapes or something? This might not effect us because we're on
localhost, but I want to make a note that this isn't implemented yet.
This also makes a small change regarding the `<label>` element --
previously we were writing them as siblings to the input and using the
`for` attribute to target the input, but while messing with the …
> Add profile edit page

- src/models.js
Problem: Other clients render a `channel` property, which is basically a
way to add a single hashtag to your post, but Oasis doesn't support
that. This means that someone might post "this is fun!" under the
channel #running and people using Oasis would just see "this is fun!"
without any context.
Solution: Add the hashtag to the bottom of the post, which visually
looks the same as someone adding two newlines and a hashtag to the end
of the text in their post.
> Show channel as text appended to posts

- src/models.js
Problem: The Extended page is sorting by received timestamp, not
asserted timestamp.
Solution: Find the `Date.now` and replace it with `Date.now()`, which
refers to the current date instead of `undefined`, which is what you get
if you try to `JSON.stringify(Date.now)`.
> Fix Extended page sorting posts incorrectly

- .cspell.json
- README.md
- docs/configuring.md
- docs/install.md
- src/index.js
Problem: The install instructions in the readme contains quotes because
it has a `*`, but `#semver:` does what we need without the quotes. The
`docs/install.md` file also has some unnecessary complexity, like
cloning via SSH (only useful for maintainers), which I think we can
safely remove.
Solution: Change the install instruction and reorganize
`docs/install.md` to be more relevant to people who are installing from
source.
> Simplify installation

- README.md
The example command `oasis` all by itself was so simple that it wasn't clearly a command-line command, so I added a sentence about it.
Also added a sentence about installing Node, geared at non-technical people.
> README.md: clarify installation instructions

- README.md
When viewing /settings/readme as linked in the setting page, there was some issues with the way README was formatted as you can see in this screenshot:
Tweak markdown so that it looks better in the browser:
> Fixed wrapping in README to improve readability of /settings/readme

- src/views/i18n.js
- src/views/index.js
Additional linguistic clarification for /publish. 
Changed "message" to "post" and adding the word "content" to the content warning text.
> Small text tweaks to /publish

- README.md
- package.json
- src/views/index.js
Problem: The SSB-Markdown library has some SSB-flavored quirks, like
messing with newline behavior, and is inappropriate for rendering plain
Markdown like the readme.
Solution: Since SSB-Markdown uses Markdown-It under the hood, we can use
the same library and just render our Markdown *without* the SSB-flavored
quirks. This gives us the ability to wrap text and avoid SSB-Markdown
problems without having to rewrite all of our Markdown.
cc: @georgeowell I think this also resolves the problem you described in #283 without rewriting any Markdown. :tada:
> Vanilla markdown

- src/views/i18n.js
- src/views/index.js
Some strings were still hardcoded and not translatable. Fixes #294 
Added a i18n string for the contentWarningPlaceholder and for "private/public" adjectives when writing a comment.
I am not super confident about my naming of the i18n strings, so I am open to other naming suggestions.
> Small i18n improvements

- README.md
Patchwork freezes on launch if Oasis is already running (because of an SSB server conflict, I assume).  I added an FAQ to guide people around that pothole.
> README: add FAQ about running alongside other SSB apps

- src/views/index.js
The link to the popular view in the navigation was broken after changing the root to /mentions.
Added direkt link to popular view instead of root.
> Fix link to popular view in navigation

- .cspell.json
- src/http.js
- src/index.js
Problem: When our views are still indexing the database they apparently
don't respond over MuxRPC, which means that we're just waiting forever
until they finish. This means that people who are indexing the database
get an HTTP response that might take an hour to finish.
Solution: If we have more than 1 mebibyte of backlog, present an error
message explaining the situation and asking for a bit of patience.
> Present error message while waiting for indexing

- .cspell.json
- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: We can set our name and profile description but profile images
are expected by most people and supported by most clients and we don't
have them. A profile without an image can sometimes lack the intimacy
you'd get if you let people upload profile images that they can use as a
visual avatar.
Solution: Add profile image upload to the Edit Profile page and add a
bunch of plumbing for `ssb.blobs.add()` to add the blob and publish a
message setting it as a profile image.
> Add profile image upload

- src/views/i18n.js
Text is ambiguous. Perhaps the full term "plain text" is better when compared to "Markdown"
Added reference to "plain text" instead of just text
> Added reference to "plain text" instead of just text

- contrib/install-systemd-service.js
Previously you would get this error due to imperfect path creation
```
node contrib/install-systemd-service.js
fs.js:114
throw err;
^
Error: ENOENT: no such file or directory, copyfile '/home/justin/src/github.com/fraction/oasis/contrib/oasis.service' -> '/home/justin/.config/systemd/user/oasis.service'
at Object.copyFileSync (fs.js:1728:3)
at Object.<anonymous> (/home/justin/src/github.com/fraction/oasis/contrib/install-systemd-service.js:27:6)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Function.Module.runMain …
```
> Fix issue w/ mkdirp race condition

- src/index.js
- src/views/index.js
Problem: The indexing message is being thrown as an error, which is
pasted as plaintext, so we can't do a page refresh. This is frustrating
when you're waiting for the indexes to finish because you have to
manually refresh a bunch while you wait.
Solution: Use the prototype from @justinabrahms to add an HTML message
for the indexing error and automatically refresh the page every ten
seconds.
> Indexing error message

- src/assets/style.css
Previously, there was a minor indent on threads, which made it visually difficult to determine which things were replies and which were new posts. 
This addresses that concern by shifting the individual cards over, which makes them visually distinct. 
Additionally, it doesn't move the sidebar over at all, so there's no weirdness as you navigate tabs.
Fixes #336
> Actually shift cards over, rather than just a minor indent.

- src/models.js
Problem: Trying to view a private message crashes the server and leaks a
bunch of memory. That's bad. This problem is caused by faulty handling
in the function that finds thread ancestors. There's some code that says
"if the next ancestor is a private message, just return the ancestors
that we know about", which returns nothing when we're looking up a
private post (because we can't identify *any* ancestors).
Solution: Ensure that we're only resolving the promise once in the
function by chaining `else if`s and ensure that we only return the
ancestor list if there are actually ancestor in it. If the ancestor list
is empty, we can just return the single message that we know about and
pass it off.
> Fix crash when linking directly to private message

- src/cli.js
- src/index.js
- src/views/i18n.js
Closes #333 
By using the existing config mechanism, this allow someone to pass in the theme as a command line arg or set the theme in `defaults.json`, while still allowing someone to set the theme on a per-browser basis as a cookie.
> Load theme using existing config mechanisms

- .cspell.json
- src/cli.js
Problem: Capitalization in "sulphurPool" was causing a file not found.
Solution: Repalce "sulphurPool" with "sulphurpool".
> Fix theme using capitalization

- .github/ISSUE_TEMPLATE.md
Problem: Almost everyone is on the latest version and we probably don't
need to ask for what version they're using.
Solution: Remove the question.
> Remove version question from issue template

- src/views/index.js
Problem: The peer list shows peers that are connected and in the process
of establishing a new connection, which has lots of turbulence. It's
confusing to see dozens of "connections" that only exist for a few
milliseconds when they're actually just connection attempts.
Solution: Only show peers with the state "connected".
> Only show connected peers in settings

- src/assets/style.css
- src/http.js
- src/views/index.js
Problem: After some fantastic new pull requests, there are some
inconsistencies between how each author implemented different features.
Solution: Fix regressions and iron out inconsistencies. This fixes the
heart highlight bug, uses the same indentation for Summaries + Threads +
the thread view, tightens up the CSP now that we don't need
unsafe-inline styles, and uses a neutral tone for indents with the same
width as the blockquote border (so far violet has been reserved for
private messages).
> Fix UI inconsistencies

- README.md
Problem: There's a chat room but it isn't in the readme.
Solution: Put it in the readme.
Fixes: https://github.com/fraction/oasis/issues/318
> Add Matrix chat room to readme

- src/models.js
Problem: When publishing a root post, other clients give you the option
of adding a `channel` property, which is basically just a hashtag. We
show this at the end of the message, but since replies often copy the
`channel` property then it gets appended to every reply.
Solution: Only append the channel as a hashtag for root posts.
> Don't append channel to non-root posts

- docs/contract.md
- docs/contributing.md
- docs/maintaining.md
Problem: We had our contract in `contributing.md` but that didn't really
give actionable information on how to contribute or how to maintain this
project.
Solution: Move contract to `contract.md` and start documents for
contributing and maintaining.
> Add contributing and maintainting documents

- src/models.js
Problem: Messages are being fetched with `post.get()`, which runs the
`transform()` function to decorate them with Markdown/etc, but then
they're being passed through `transform()` a second time at the end of
the function. This is inefficient and applies side-effects (like adding
channels to the post) twice.
Solution: Remove the final `transform()` so that these posts are only
decorated once.
Fixes: https://github.com/fraction/oasis/issues/358
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `curl http://old/public/popular/day` | 908.5 ± 59.2 | 851.9 | 998.5 | 1.42 ± 0.16 |
| `curl http://new/public/popular/day` | 641.2 ± 57.2 | 579.6 | 751.6 | 1.00 |
> Avoid processing popular posts twice

- src/ssb.js
Problem: By default we only connect to people that we're directly
following, which often don't have public IP addresses.
Solution: Automatically connect to all available peers within our
replication hops (default 2) to make peering more reliable.
> Automatically connect to replicated peers

- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: We have a way to follow and unfollow, but there's no way to
block or unblock. Also if you go to the profile of a blocked peer, their
posts still show up.
Solution: Add block and unblock and hide messages from blocked peers on
their profile page.
Fixes: https://github.com/fraction/oasis/issues/370
> Add block and unblock to author profile

- src/assets/style.css
> Fix z-index on sticky header

- src/models.js
Previous query incorrectly pulled and sorted posts, often showing years
old posts from newly followed people.
This now behaves more consistently
as "recent threads from people in your extended network".
> Updates query for threads

- src/assets/style.css
- src/models.js
- src/views/index.js
- Adds a hover popup that shows the names of everyone who liked a post
when hovering of the heart.
- Add new call to post.get that retrieves the names of all voters and
returns them instead of their ID's.
I added the extra "like" class to make the css more specific, didn't want to apply the hover effect to all buttons. 
Fixes #256 
A simple hover on all hearts that shows who liked something. Here's how it looks for a post with a few likes:
And a post with many likes:
Happy to make changes to CSS to fit Oasis better, I'm not the best designer.
> Show who liked content on hover

- src/assets/style.css
- src/views/index.js
- Instead of having a custom on hover effect, just add the Liked by
message to the title of the heart.
- When there are > 16 likes on a post, show +X more to convey this to
users.
- Removed the old css code and the 'like' class on the button, reverting CSS changes in #377 
Fixed #380 
Making the liked-by popup more accessible to non-mouse users. Also better for future maintainence as it doesn't require additional CSS or classes. 
Showing liked-by via title attribute, as described in #380
> Show liked-by in title attr, handle many likes

- src/views/i18n.js
- src/views/index.js
Problem: #367 doesn't pass the linter.
Solution: Run `npm run fix` and disable the spell-checker when we
define language names.
> Fix linter problems with Italian translation

- src/assets/style.css
Problem: Footer buttons have the normal button background hover state
that makes them difficult to read. This was meant to be fixed in another
PR but I think I got the CSS order wrong.
Solution: Reorder the CSS hierarchy to fix the bug. For real this time.
Fixes: #357
> Fix footer button hover background

- .mailmap
Problem: Some of us have a few different emails, which show up as
different people when we commit. It would be great to merge these Git
identities so that they don't show up as different people.
Solution: Use `.mailmap`, which lets people choose their favorite
canonical email address for this project.
> Add .mailmap for canonical identities

- src/ssb.js
Problem: I made a bad merge in 2836c80 which broke the server in some
environments. I had issues running the globablly installed binary,
whereas `npm start` seemed to work fine. Anyway, there's an error about
some missing config options because we weren't importing SSB-Config into
the server configuration. Instead, the full config was just:
```json
{ "conn": { "autostart": true } }
```
This lacks important properties like `shs`, which means that the server
can't start. Fun!
Solution: Pass SSB-Config first and then overlay our custom config on
top. I've also added comments and changed the variable names so that
this is harder to miss in the future.
> Fix config bug

- .prettierignore
- package-lock.json
- package.json
- src/http.js
- src/index.js
- src/ssb.js
- test/basic.js
- test/lifecycle.js
Problem: ESLint and TypeScript help catch some types of regressions, but
they don't protect us against obvious stuff like "the server won't
start". This means that humans need to test a bunch of stuff manually,
and that can be really tedious and exhausting.
Solution: Yesterday someone invented this cool concept called "testing"
where you write automated tests for your software to ensure it actually
works the way you expect. It might have beeen invented before yesterday,
I don't know. Anyway, this solution adds a bunch of tests that send HTTP
GET requests to a bunch of endpoints to make sure the server is at least
returning HTTP 200 responses. It also fixes a race condition where HTTP
server was available before the readme / version strings were loaded.
> Add very basic test suite

- src/cli.js
- src/http.js
- src/index.js
Problem: When proxying Oasis, the CSRF + DNS rebind security precautions
will respond with HTTP 400 if you use a hostname that Oasis doesn't
know about. For example, if Oasis is listening on `localhost` and you
use Caddy/Nginx/etc to proxy that to `oasis.example.com`, then Oasis
will see GET requests as DNS rebind attacks and POST requests as CSRF
attacks.
Solution: Add `--allow-host` command-line flag so that you can
`--allow-host oasis.example.com` and ensure that the host is allowed by
the security measures.
> Add --allow-host CLI flag for for proxy use-case

- docs/contributing.md
Problem: I wrote "tpo". I meant "typo".
Solution: Fix the tpo.
> Fix "tpo" typo

- src/http.js
Problem: Unfortunately `setImmediate()` doesn't actually ensure that
`server !== null`, so we can get fun race condition errors that have
been reported on Windows.
Solution: Replace `setImmediate()` hack with event emitter that actually
ensures that the server is listening (and hopefully isn't `null)`.
Fixes: https://github.com/fraction/oasis/issues/401
> Replace setImmediate() with .on('listening')

- src/ssb.js
Problem: During a refactor the SSB connection management was changed to
be more conservative, so it only ensures that we have a connection once
the server is started. This isn't good, because it means `oasis
--no-open` no longer starts an SSB service in the background.
Solution: Run `ensureConnection()` to ensure that we have a connection
to the SSB service regardless of regardless of whether we've received
any requests over HTTP.
---
See: `%feSvhuLLa8vA475+k1Z9ZWEAHvNhYTT1H4wlpcoGEYw=.sha256`
> Start SSB service immediately instead of waiting

- src/views/index.js
Problem: The FR translation is added in `i18n.js` but it's not available
in the drop-down language selection menu.
Solution: Add it to the menu and ensure that the menu is sorted
alphabetically by the name of the language.
> Add Français (FR) to the language drop-down

- .cspell.json
- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Constant network activity of connecting to peers and streaming of data can be really busy and distracting. "Sync" allows you to keep Oasis running in offline mode and sync when you want to get new stuff. Sync can be expanded upon in the future to be more useful when calling from a script.
Relates to #354. 
When clicking "Connect and Sync" in settings, Oasis starts the connection scheduler, waits until you're connected to peers, waits for items to download, and then disconnects from peers.
This is best used when running Oasis in offline mode. It's basically useless in "normal" mode and will actually stop the connection scheduler and disconnect you from connected peers, which may be unexpected if you're not already offline. This could probably be improved upon.
> Introduces sync endpoint

- src/models.js
Problem: The sync goes forever, which isn't good if we're in an edge
case (like having peers who are offline with us).
Solution: Add a 5-minute timeout and refactor to use a design that's
maybe simpler? This is just my stab at the previous behavior, but there
are definitely improvements that could be made!
> Add timeout to sync and refactor

- src/cli.js
Problem: The preset for allow-host is coming from "host".
Solution: Make the preset for allow-host come from "allow-host".
> Fix allow-host preset not working correctly

- src/assets/style.css
Problem: The "metric CSS" was kind of clever but mostly just confusing.
Solution: Use `--size-N` for the size, where the size is `2^n`. Double
size is `--size-1`, half size is `--size--1` (negative one). The
negatives kind of suck but I couldn't think of a better solution that
didn't give up the flexibility, brevity, or the ability to sort
alphabetically.
Fixes: https://github.com/fraction/oasis/issues/100
> Replace "metric CSS" with --size-N

- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: The words "comment" and "reply" are super ambiguous, but
renaming them is hard.
Solution: I think "subtopic" captures the sentiment well, and makes it
clear that you're leaving the current topic to start a new topic (rather
than just replying to an individual message).
Fixes: #27
> Rename "reply" to "subtopic"

- src/assets/style.css
Problem: the `<summary>` element had a broken bottom margin on content
warnings, and isn't obvious that it's not just text.
Solution: Fix the margin and used a dashed border to indicate that the
content can be expanded. I think this is more intuitive than no border,
and I think the dashed line draws parallels with "cut outs" that might
make expansion intuitive (?), but either way I think it's better than
the previous design.
> Fix summary style

- src/views/i18n.js
- src/views/index.js
Closed #55 by adding view specific `<title>`. 
Uses `i18n` translation or non-language specific attributes like author name or snippet. Instead of implementing any new `ssb-markdown` functionality as mentioned in the issue, I just used the existing `postSnippet()` function that's used in subtopic previews to get a snippet of the message content.
I would welcome any feedback on implementation or by happy to make any desire changes.
> Adds view specific titles

- src/assets/style.css
- src/views/index.js
Section headers were poorly wrapping on tiny screens.
[Before Screenshot](https://user-images.githubusercontent.com/1012017/81691662-2bf1e880-942b-11ea-947d-1587c437012b.png) | [After Screenshot](https://user-images.githubusercontent.com/1012017/81691688-3318f680-942b-11ea-8303-ea444f49cc6f.png)
Some flex options to fill space and wrap.
> Improve wrapping of sticky section header

- src/assets/style.css
- src/views/index.js
When using a text browser (w3m in my case), it's hard to distinguish between different threads in the Summaries and Threads view. The indentation and CSS-based left border on comments and subtopics don't render in text-based browsers.
There was very little visual distinction when the comments on a thread ended and when the next thread begins:
Introduce a `<hr>` after a thread. This is determined by when a message `isRoot` and has `aside`.
The `text-browser` class is added to `display: none;` in CSS. In effect, this PR makes no change to graphical browsers and only displays the horizontal rule when browsers that don't use CSS. This seems to be a better approach than my last attempt (#364).
> Adds visual separator between different threads

- .dockerignore
- contrib/Dockerfile
- docs/with-docker.md
Problem: The Docker example was using Alpine with the Tini dependency
and some neat custom stuff, but it wasn't super clear to understand
everything that was going on. It was also slow because lots of stuff was
compiling from source.
Solution: Replace neat custom stuff with boring defaults for clarity and
much faster builds.
> Refactor Docker example

- src/views/index.js
Profile Edit was broken because I missed adding the `titlePrefix` parameter. Closes #446.
Add it.
> Fix broken Profile Edit

- src/views/markdown.js
This allows blobs to load when the blob reference in the markdown has
`?contentType=image/jpeg` or similar hints attached.
It does so by simply removing the GET parameters from the URL though.
It would be a bit nicer to actually use those hints to set the right
HTTP response headers, but somehow koa keeps ignoring / overwriting (?)
the manually-set `Content-Type` headers, so this has to do for now.
> Allow GET params in /blob calls.

- src/views/index.js
Oh, so Christian's birthday was "1y ago"? But when *exactly* was that?
Hover the timestamp to find out! :)
Needing to know the exact time something was posted.
A tooltip over the UI element that shows the relative time. It's a classic pattern I guess?
> Add absolute post time as tooltip to timestamps.

- .cspell.json
- package-lock.json
- package.json
- src/index.js
- src/models.js
- test/basic.js
Problem: Recently there was a PR [0] merged with a quickfix to avoid
some test failures, which is something I've been trying to avoid. While
`process.exit()` works fine, I'm worried that it means we don't
understand what's happening under the hood, *plus* I have the [maybe
unjustified?] worry that it might kill the process during a database
write or something dangerous. It looks like this particular test hang
was caused by both a stream and some number of intervals that were left
open.
Solution: Provide a way to close the stream and intervals in `index.js`
and ensure that we do that before closing the server.
[0]: https://github.com/fraction/oasis/pull/462
cc: @cryptix @cblgh @black-puppydog @cinnamon-bun
> Fix tests and remove workaround

- src/index.js
Problem: You can't publish email addresses or user@host combos or
anything like that because the regex is super liberal in what it
matches.
Solution: Ensure that the first word in a message is a mention *or*
ensure that there's whitespace before a mention. This also adds a
regex101 link (in lieu of proper testing, for now) which makes this
easier to test and track over time.
---
See-also: https://github.com/fraction/oasis/issues/466
> Use stricter regex for @mention match

- .github/dependabot.yml
- .github/workflows/pr.yml
Problem: 5 is not a lot and I'd rather have the builds all done and
ready when I'm ready to merge them instead of having to do them in
chunks of 5.
Solution: Allow 16 open PRs at a time. We can change as needed.
> Increase dependabot open PR limit

- .huskyrc
- docs/contributing.md
- package-lock.json
- package.json
Problem: I keep forgetting to run tests and my commits aren't actually
passing in CI. I'd really like for these to be run automatically so that
I don't have to remember my pre-commit hooks.
Solution: Revert commit d9e829e2e8eddcc7c8edae2dd542cb69d86836c1, which
Nick Wynja added to remove Husky as a pre-commit hook. I hope that
anyone who doesn't want to run the pre-commit hook will run Git with the
`--no-verify` option, and anyone bummed at this change will open a
conversation to discuss in more details (or just revert *this* commit).
---
See-also: https://github.com/fraction/oasis/issues/346
> Revert "Removes husky to fix #346"

- src/assets/style.css
Problem: There were lots of CSS changes in the preview + blob PR and I
didn't take enough time to look at them. It looks like a few of them
made style problems (e.g. extra specing in the 'next' / 'previous' links
on the profile pages) and it made it harder (IMO) to determine that
links are links (since we've been using font weight to distinguish).
Solution: Revert those changes back to the previous defaults. If the
margin glitch was on purpose or anyone feels strongly about
distinguishing links using some other style (color?) then I'm happy to
merge those, but I'd like to fix the extra margin and have *some* way to
distinguish links in the mean time.
> Revert CSS changes from preview PR

- src/index.js
- src/models.js
- src/views/i18n.js
- src/views/index.js
Problem: The latest release seems to have some index problems, which is
frustrating, but might be able to be circumvented with a database
rebuild. The rebuild was something that Ahau funded and I'm excited to
be able to finally expose this to users without asking them to `rm -rf`
random files in their `~/.ssb` directory.
Solution: Replaced unused 'progress' bars (always at 100%) with rebuild
button.
> Add rebuild button to settings

- docs/configuring.md
- src/index.js
- src/views/index.js
Adjusting stylesheet values to change things such as the main content width requires editing the stylesheets included in the oasis source code.
Allowing the user to modify stylesheet values such as content width using a stylesheet file saved in their oasis configuration folder.
> Add support for linking an optional custom-style.css file from the user's oasis configuration folder.

- src/assets/style.css
- src/models.js
- src/views/i18n.js
- src/views/index.js
#622 
This introduces a basic implementation to not display the content of
messages. It still shows that a message exists but shows localized
copy indicating why the content was hidden.
We should consider additional filters or queries in different views to actually
remove these posts but I'll leave that as up for discussion since I can see
value in showing that a blocked comment exists in a conversation.
> Hides content of messages from blocked people

- src/index.js
- src/models.js
- src/views/index.js
Subscribed channels make it easy to stay connected to topics you're interested in. Oasis doesn't display a list of topics anywhere so, as mentioned in #217, you need to access through search and then click on a hashtag.
Any subscribed channels now appear at the top of Topics. This gives you
easy access to view subscribed channels using the existing hashtags
view. Much more can be done to fully support features discussed in #217 but this is a start.
For anyone reviewing, you can subscribe and unsubscribe to channels with these CLI commands:
```
ssb publish --type channel --channel oasis --subscribed
```
and:
```
ssb publish --type channel --channel oasis --no-subscribed
```
> Adds subscribed channels to Topics

- docs/with-docker.md
The oasis wouldn't be reachable at `localhost:3000`.
Use 127.0.0.1 for the host side of the mapping (localhost), rather than the incorrect 127.0.0.0.
> docs: Fix Docker port mapping
